#server:
#  port: 9000
#
#spring:
#  application:
#    name: pineconemall-order
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.103.189.107:3306/pineconemall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
#    username: root
#    password: s300056.
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 39.103.189.107:8848
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto