spring:
  rabbitmq:
    host: 39.103.189.107
    virtual-host: /
    # 开启发送端消息抵达broker确认
    publisher-confirm-type: correlated
    # 开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，就以异步方式优先回调我们这个returnconfirm
    template:
      mandatory: true
    # 手工模式确认，手动ack消息
    listener:
      simple:
        acknowledge-mode: manual
  session:
    store-type: redis
  # 格式化日期，让String可以强转Date 一定要这样写
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

ribbon:
  eager-load:
    enabled: true
    clients:
      - pineconemall-cart
      - pineconemall-member
      - pineconemall-product
      - pineconemall-ware
  ReadTimeout: 60000
  ConnectTimeout: 60000

# 设置session过期时间，十分钟
server:
  servlet:
    session:
      timeout: 600

pineconemall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10