spring:
  cloud:
    gateway:
      routes:

        - id: product-route
          uri: lb://pineconemall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: member-route
          uri: lb://pineconemall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: ware-route
          uri: lb://pineconemall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: third-party
          uri: lb://pineconemall-thrid-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates :
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}
          # http://localhost:88/captcha.jpg ==> http://localhost:8080/renren-fast/captcha.jpg