spring:
  cloud:
    gateway:
      routes:

        - id: product-route
          uri: lb://pineconemall-product
          predicates:
            - Path=/api/product/**, /hello
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: member-route
          uri: lb://pineconemall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: ware-route
          uri: lb://pineconemall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: third-party
          uri: lb://pineconemall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/$\{segment}

        - id: admin-route
          uri: lb://renren-fast
          predicates :
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}
          # http://localhost:88/captcha.jpg ==> http://localhost:8080/renren-fast/captcha.jpg

        - id: pineconemall-host/detail-route
          uri: lb://pineconemall-product
          predicates:
            - Host=pineconemall.com,item.pineconemall.com
        - id: pineconemall-search-route
          uri: lb://pineconemall-search
          predicates:
            - Host=search.pineconemall.com
        - id: pineconemall-auth-server-route
          uri: lb://pineconemall-auth-server
          predicates:
            - Host=auth.pineconemall.com