spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000 #ms
      #key-prefix: CACHE_ #指定了前缀就使用指定的，如果没有就默认使用缓存的名字作为前缀
      #use-key-prefix: false #不使用缓存的名字作为前缀
      cache-null-values: true #是否缓存空值，防止缓存穿透，一定要用
  session:
    store-type: redis

ribbon:
  eager-load:
    enabled: true
    clients:
      - pineconemall-coupon
      - pineconemall-search
      - pineconemall-seckill
      - pineconemall-ware
  ReadTimeout: 60000
  ConnectTimeout: 60000

# 设置session过期时间，十分钟
server:
  servlet:
    session:
      timeout: 600

pineconemall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10