ribbon:
  eager-load:
    enabled: true
    clients:
      - pineconemall-member
      - pineconemall-third-party
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  session:
    store-type: redis
# 设置session过期时间，十分钟
server:
  servlet:
    session:
      timeout: 60m

      #  cloud:
      #    alibaba:
      #      seata:
      #        tx-service-group: pineconemall-auth-server