#spring:
#  cloud:
#    alicloud:
#      access-key:
#      secret-key:
#      oss:
#        endpoint: oss-cn-zhangjiakou.aliyuncs.com
#      sms:
#        host: https://gyytz.market.alicloudapi.com
#        path:
#        appcode:
#        sms-sign-id:
#        template-id: