ribbon:
  eager-load:
    enabled: true
    clients:
      - pineconemall-order
      - pineconemall-coupon
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  session:
    store-type: redis
  redis:
    host: 39.103.189.107
server:
  servlet:
    session:
      timeout: 600